name: "codefixguy"
description: "Automate code quality fixes for Python, JS, TS, Java, and Go"
author: "<Your Name>"

branding:
  icon: "tool"
  color: "#1976D2"

inputs:
  github-token:
    description: "GitHub token with repo scope"
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    # Check out FixGuy repo to access requirements.txt
    - name: Checkout FixGuy repo
      uses: actions/checkout@v4
      with:
        repository: username/fixguy  # Replace 'username' with your GitHub username
        path: fixguy-action

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fixguy-action/requirements.txt  # Point to the checked-out requirements.txt
      shell: bash
    
    - name: Set up Node.js for ESLint
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install ESLint
      run: npm install eslint --global
      shell: bash
    
    - name: Set up Java for Checkstyle
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
    - name: Install Checkstyle
      run: |
        wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.17.0/checkstyle-10.17.0-all.jar
        sudo mv checkstyle.jar /usr/local/lib/
      shell: bash
    
    - name: Set up Go for Staticcheck
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
    - name: Install Staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
      shell: bash
    
    # Check out the user's repo for linting
    - name: Checkout user's repo
      uses: actions/checkout@v4
      with:
        path: user-repo

    - name: Run FixGuy
      run: python -m main "${{ github.repositoryUrl }}" "${{ inputs.github-token }}"
      working-directory: fixguy-action  # Run from FixGuy's directory
      shell: bash