name: FixGuy

on:
  schedule:
    - cron: "0 0 * * 0"  # Weekly on Sunday at midnight UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  fixguy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run FixGuy
        env:
          GITHUB_TOKEN: ${{ secrets.FIXGUY_TOKEN }}
          REPO_URL: ${{ github.repositoryUrl }}
        run: |
          python -m fixguy.main "$REPO_URL" "$GITHUB_TOKEN"
